name: Sync Others

on:
  schedule:
    - cron: '* */5 * * *' # 每3小时触发, 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点
jobs:
  repo-sync:
    name: Sync Others
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: GitHub Repo Sync
      uses: repo-sync/github-sync@v2.3.0
      with:
        source_repo: https://github.com/ggborr/aweikeji
        source_branch: main
        destination_branch: aweikeji
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2.3.4
      with:
        ref: aweikeji
    - name: Judge Time
      id: in5Hours
      run: |
        export hourAgo=$(git show --pretty=format:"%cr" | head -n 1 | awk '{if($2=="hours" && $1<=5) print($1);else if($2!="days") print($1)}')
        echo "::set-output name=in5Hours::$hourAgo"
        echo $hourAgo
    - name: Get Newest File
      id: lastestFile
      if: ${{ steps.in5Hours.outputs.in5Hours }} 
      run: |
        export lastestfile="$(ls -l | awk '{print $9}' | grep -e "keji$" | sort -n |tail -n 1)"
        echo "::set-output name=lastestFile::$lastestfile"
        echo $lastestfile
    - uses: actions/checkout@v2.3.4
      with:
        ref: main
    - name: Move files
      id: gitStatus
      if: ${{ steps.lastestFile.outputs.lastestFile }}
      run: |
          git checkout origin/aweikeji ${{ steps.lastestFile.outputs.lastestFile }}
          mv ${{ steps.lastestFile.outputs.lastestFile }} clash_auto
          git rm ${{ steps.lastestFile.outputs.lastestFile }}
          git add clash_auto
          echo "::set-output name=gitStatus::$(git status -s)"
          echo $(git status -s)
    - name: Commit files
      if: ${{ steps.gitStatus.outputs.gitStatus }}
      run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Update Clash Auto" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
