name: Sync Others

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
jobs:
  repo-sync:
    name: Sync Others
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0
    - name: Merge files
      id: gitStatus
      run: |
          source ./moveProxiesToSync.sh
          git remote add aweikeji "https://github.com/ggborr/aweikeji"
          git fetch aweikeji --depth=2

          git remote add TopFreeProxies "https://github.com/alanbobs999/TopFreeProxies"
          git fetch TopFreeProxies --depth=2
          
          aweikejiFile=$( git diff --name-only --diff-filter=AMT aweikeji/main~1 aweikeji/main  | xargs -I{} -- git log -1  --remotes="aweikeji"  --format="%ci {}" -- {} | sort | tail -1 | cut -d " " -f4)
          
          git checkout aweikeji/main "$aweikejiFile"
          git checkout TopFreeProxies/master "Eternity.yaml"
          
          echo "proxies:" > clash_auto 
          moveProxiesToSync "$aweikejiFile" clash_auto
          moveProxiesToSync "Eternity.yaml" clash_auto
          
          git rm -rf "$aweikejiFile"
          git rm -rf "Eternity.yaml" 
          
          git add clash_auto
          gitStatus="$(git status -s)"
          echo "hadChanged=${#gitStatus}" >> $GITHUB_OUTPUT
    - name: Commit files
      if: ${{ steps.gitStatus.outputs.hadChanged != 0 }}
      run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Update Clash Auto" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
