name: Sync Others

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
jobs:
  repo-sync:
    name: Sync Others
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0
    - name: GitHub Repo Sync
      uses: repo-sync/github-sync@v2.3.0
      with:
        source_repo: https://github.com/ggborr/aweikeji
        source_branch: main
        destination_branch: aweikeji
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2.5.0
      with:
        ref: aweikeji
    - name: Latest CommitFile
      id: latestCommitFile
      run: |
        git fetch origin aweikeji --depth=2
        latestFile=$(git diff --name-only --diff-filter=AMT HEAD~1 HEAD | xargs -I{} -- git log -1 --format="%ci {}" {} | sort | tail -1)
        echo "latestCommitFile=$latestFile" >> $GITHUB_OUTPUT
        echo $latestFile
    - uses: actions/checkout@v2.5.0
      with:
        ref: main
    - name: Judge Time
      id: judgeTime
      if: ${{ steps.latestCommitFile.outputs.latestCommitFile }} 
      run: |
        if [[ -f _time ]]; then
          record=$(head -1 _time)
        else
          touch _time
        fi
        
        lastestCommitFile="${{ steps.latestCommitFile.outputs.latestCommitFile }}"
        if [ "$record" != "$lastestCommitFile" ]; then
          doFlag=true
        fi
      
        echo $lastestCommitFile > _time
        git add _time
        echo "doFlag=$doFlag" >> $GITHUB_OUTPUT
        echo $doFlag
    - name: Move files
      id: gitStatus
      if: ${{ steps.judgeTime.outputs.doFlag }}
      run: |
          remoteFileName=$(echo "${{ steps.latestCommitFile.outputs.latestCommitFile }}" | cut -d " " -f4)
          git checkout origin/aweikeji $remoteFileName
          mv $remoteFileName clash_auto
          git rm $remoteFileName
          git add clash_auto
          gitStatus="$(git status -s)"
          echo "hadChanged=${#gitStatus}" >> $GITHUB_OUTPUT
          echo $gitStatus
    - name: Commit files
      if: ${{ steps.gitStatus.outputs.hadChanged }}
      run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Update Clash Auto" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
